// =============================================================
//  auth.js — Authentication & Session Management
//  MoodSync · Signup, login, logout, guards, profile access
//
//  Dependencies: supabaseClient.js (must load first)
//
//  Public API:
//    getUser()              → current Supabase auth user | null
//    getProfile(userId?)    → profiles row | null
//    getCouple()            → couples row | null
//    getPartnerId(couple, userId) → partner's UUID
//    signUp(name, email, pw)
//    signIn(email, pw)
//    signOut()
//    requireAuth()          → guard: redirects to login if unauthed
//    requireCouple()        → guard: redirects to pair if unpaired
//    redirectAfterAuth()    → smart redirect based on pairing state
//
//  Also handles login.html and create-account.html form logic
//  via DOMContentLoaded page detection.
// =============================================================

"use strict";

// =============================================================
//  Auth API
// =============================================================

/**
 * Get the currently authenticated Supabase user.
 * @returns {Promise<Object|null>}
 */
async function getUser() {
    const { data: { user } } = await supabaseClient.auth.getUser();
    return user;
}

/**
 * Get a user's profile from the profiles table.
 * Falls back to the current user if no userId is given.
 * @param {string} [userId]
 * @returns {Promise<Object|null>}
 */
async function getProfile(userId) {
    const uid = userId || (await getUser())?.id;
    if (!uid) return null;

    const { data, error } = await supabaseClient
        .from("profiles")
        .select("*")
        .eq("id", uid)
        .single();

    if (error) { console.error("[auth.getProfile]", error.message); return null; }
    return data;
}

/**
 * Get the couple record for the current user (if paired).
 * @returns {Promise<Object|null>}
 */
async function getCouple() {
    const user = await getUser();
    if (!user) return null;

    const { data, error } = await supabaseClient
        .from("couples")
        .select("*")
        .or(`user1_id.eq.${user.id},user2_id.eq.${user.id}`)
        .limit(1)
        .maybeSingle();

    if (error) { console.error("[auth.getCouple]", error.message); return null; }
    return data;
}

/**
 * Return the partner's user_id from a couple record.
 * @param {Object} couple
 * @param {string} userId - The current user's id
 * @returns {string}
 */
function getPartnerId(couple, userId) {
    return couple.user1_id === userId ? couple.user2_id : couple.user1_id;
}

/**
 * Sign up a new user + create their profiles row.
 * The pair_code is auto-generated by the Postgres default.
 * @param {string} name
 * @param {string} email
 * @param {string} password
 * @returns {Promise<Object>} Supabase user
 */
async function signUp(name, email, password) {
    const { data, error } = await supabaseClient.auth.signUp({
        email: email.trim().toLowerCase(),
        password,
        options: { data: { name: name.trim() } },
    });

    if (error) throw error;
    if (!data.user) throw new Error("Signup failed — no user returned.");

    // The DB trigger (handle_new_user) creates the profile row automatically using
    // raw_user_meta_data.name. If a session is immediately available (email
    // confirmation disabled in Supabase), we also run an update to guarantee the
    // name is correct. update satisfies the RLS update policy (auth.uid() = id)
    // without needing to insert, so it works regardless of the trigger state.
    if (data.session) {
        const { error: profileErr } = await supabaseClient
            .from("profiles")
            .update({ name: name.trim() })
            .eq("id", data.user.id);

        if (profileErr) {
            // Non-fatal: trigger already populated the row from metadata
            console.warn("[auth.signUp] Profile name update failed:", profileErr.message);
        }
    }

    return data.user;
}

/**
 * Sign in with email + password.
 * @returns {Promise<Object>} Supabase user
 */
async function signIn(email, password) {
    const { data, error } = await supabaseClient.auth.signInWithPassword({
        email: email.trim().toLowerCase(),
        password,
    });
    if (error) throw error;
    return data.user;
}

/**
 * Sign out and redirect to login.
 */
async function signOut() {
    await supabaseClient.auth.signOut();
    window.location.href = "login.html";
}

/**
 * Determine where to send an authenticated user.
 * Paired → mood.html · Unpaired → pair.html
 */
async function redirectAfterAuth() {
    const couple = await getCouple();
    window.location.href = couple ? "mood.html" : "pair.html";
}

// =============================================================
//  Guards — call at the top of protected page initialisers
// =============================================================

/**
 * Require an authenticated session.
 * Redirects to login.html if no session.
 * @returns {Promise<Object|null>} user
 */
async function requireAuth() {
    const user = await getUser();
    if (!user) { window.location.replace("login.html"); return null; }
    return user;
}

/**
 * Require auth + an active couple.
 * Redirects to pair.html if not paired.
 * @returns {Promise<{user: Object, couple: Object, dissolutionStatus: Object}|null>}
 */
async function requireCouple() {
    const user = await requireAuth();
    if (!user) return null;

    const couple = await getCouple();
    if (!couple) { window.location.replace("pair.html"); return null; }

    // Check dissolution status (from data.js)
    let dissolutionStatus = null;
    if (typeof getDissolveStatus === "function") {
        try {
            dissolutionStatus = await getDissolveStatus();
        } catch (err) {
            console.warn("[auth] Could not fetch dissolution status:", err);
        }
    }

    return { user, couple, dissolutionStatus };
}

// =============================================================
//  Page-specific DOM logic (login + create-account)
// =============================================================

document.addEventListener("DOMContentLoaded", async () => {
    const page = window.location.pathname.split("/").pop() || "index.html";

    // -- Global logout button (present on multiple pages) ---------
    const logoutBtn = document.getElementById("logoutBtn");
    if (logoutBtn) {
        logoutBtn.addEventListener("click", (e) => { e.preventDefault(); signOut(); });
    }

    // -- Login page -----------------------------------------------
    if (page === "login.html") {
        const user = await getUser();
        if (user) { await redirectAfterAuth(); return; }
        _initLoginForm();
    }

    // -- Signup page ----------------------------------------------
    if (page === "create-account.html") {
        const user = await getUser();
        if (user) { await redirectAfterAuth(); return; }
        _initSignupForm();
    }

    // -- Forgot password page -------------------------------------
    if (page === "forgot-password.html") {
        _initForgotPasswordForm();
    }
});

// ---- Login form ----
function _initLoginForm() {
    const form        = document.getElementById("loginForm");
    const emailInput  = document.getElementById("loginEmail");
    const pwInput     = document.getElementById("loginPassword");
    const submitBtn   = document.getElementById("loginBtn");
    const formError   = document.getElementById("formError");
    const toggleBtn   = document.getElementById("togglePassword");
    if (!form) return;

    // Toggle password visibility
    if (toggleBtn && pwInput) {
        toggleBtn.addEventListener("click", () => {
            const show = pwInput.type === "password";
            pwInput.type = show ? "text" : "password";
            const icon = document.getElementById("eyeIcon");
            if (icon) icon.textContent = show ? "🙈" : "👁";
        });
    }

    form.addEventListener("submit", async (e) => {
        e.preventDefault();
        const email = emailInput.value.trim();
        const pw    = pwInput.value;

        if (!email || !pw) { _showErr(formError, "Enter both email and password."); return; }

        submitBtn.disabled  = true;
        submitBtn.innerHTML = '<span class="btn__icon">⏳</span> Signing in…';
        _hideErr(formError);

        try {
            await signIn(email, pw);
            submitBtn.innerHTML = '<span class="btn__icon">✅</span> Success!';
            await redirectAfterAuth();
        } catch (err) {
            submitBtn.disabled  = false;
            submitBtn.innerHTML = '<span class="btn__icon">✨</span> Sign In';
            _showErr(formError, _friendlyError(err.message));
        }
    });
}

// ---- Signup form ----
function _initSignupForm() {
    const form             = document.getElementById("signupForm");
    const nameInput        = document.getElementById("signupName");
    const emailInput       = document.getElementById("signupEmail");
    const pwInput          = document.getElementById("signupPassword");
    const confirmPwInput   = document.getElementById("signupConfirmPassword");
    const submitBtn        = document.getElementById("signupBtn");
    const formError        = document.getElementById("formError");
    const toggleBtn        = document.getElementById("togglePassword");
    const toggleConfirmBtn = document.getElementById("toggleConfirmPassword");
    if (!form) return;

    if (toggleBtn && pwInput) {
        toggleBtn.addEventListener("click", () => {
            const show = pwInput.type === "password";
            pwInput.type = show ? "text" : "password";
            const icon = document.getElementById("eyeIcon");
            if (icon) icon.textContent = show ? "🙈" : "👁";
        });
    }

    if (toggleConfirmBtn && confirmPwInput) {
        toggleConfirmBtn.addEventListener("click", () => {
            const show = confirmPwInput.type === "password";
            confirmPwInput.type = show ? "text" : "password";
            const icon = document.getElementById("eyeIconConfirm");
            if (icon) icon.textContent = show ? "🙈" : "👁";
        });
    }

    form.addEventListener("submit", async (e) => {
        e.preventDefault();
        const name      = nameInput.value.trim();
        const email     = emailInput.value.trim();
        const pw        = pwInput.value;
        const confirmPw = confirmPwInput ? confirmPwInput.value : pw;

        if (!name || name.length < 2) { _showErr(formError, "Name must be at least 2 characters."); return; }
        if (!email || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) { _showErr(formError, "Enter a valid email."); return; }
        if (!pw || pw.length < 6) { _showErr(formError, "Password must be at least 6 characters."); return; }
        if (pw !== confirmPw) { _showErr(formError, "Passwords do not match."); return; }

        submitBtn.disabled  = true;
        submitBtn.innerHTML = '<span class="btn__icon">⏳</span> Creating account…';
        _hideErr(formError);

        try {
            await signUp(name, email, pw);
            submitBtn.innerHTML = '<span class="btn__icon">✅</span> Account created!';
            setTimeout(() => { window.location.href = "pair.html"; }, 600);
        } catch (err) {
            submitBtn.disabled  = false;
            submitBtn.innerHTML = '<span class="btn__icon">✨</span> Create Account';
            _showErr(formError, _friendlyError(err.message));
        }
    });
}

// ---- Forgot password form ----
function _initForgotPasswordForm() {
    const form       = document.getElementById("forgotForm");
    const emailInput = document.getElementById("forgotEmail");
    const submitBtn  = document.getElementById("forgotBtn");
    const formError  = document.getElementById("formError");
    const successMsg = document.getElementById("successMsg");
    if (!form) return;

    form.addEventListener("submit", async (e) => {
        e.preventDefault();
        const email = emailInput.value.trim();
        if (!email || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
            _showErr(formError, "Enter a valid email address.");
            return;
        }

        submitBtn.disabled  = true;
        submitBtn.innerHTML = '<span class="btn__icon">⏳</span> Sending…';
        _hideErr(formError);

        try {
            const { error } = await supabaseClient.auth.resetPasswordForEmail(
                email.toLowerCase(),
                { redirectTo: window.location.origin + "/login.html" }
            );
            if (error) throw error;

            form.hidden = true;
            if (successMsg) successMsg.hidden = false;
        } catch (err) {
            submitBtn.disabled  = false;
            submitBtn.innerHTML = '<span class="btn__icon">✉️</span> Send Reset Link';
            _showErr(formError, _friendlyError(err.message));
        }
    });
}

// ---- Helpers ----
function _showErr(el, msg) { if (el) { el.textContent = msg; el.hidden = false; } }
function _hideErr(el)      { if (el) { el.textContent = "";  el.hidden = true;  } }

function _friendlyError(msg) {
    if (msg.includes("Invalid login"))       return "Incorrect email or password.";
    if (msg.includes("Email not confirmed")) return "Check your inbox to verify your email first.";
    if (msg.includes("already registered"))  return "An account with this email already exists.";
    if (msg.includes("rate limit"))          return "Too many attempts — please wait a moment.";
    if (msg.includes("network"))             return "Network error. Check your connection.";
    return msg || "Something went wrong. Please try again.";
}
